server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heron?characterEncoding=utf-8&useSSL=false
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: webiste.lhc.heron.model
logging:
  level:
    webiste:
      lhc:
        heron:
          mapper: debug
