server:
  port: 8087
spring:
  datasource:
    username: 111
    password: 111
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:2222/heron?characterEncoding=utf-8&useSSL=false
  thymeleaf:
    cache: false
    suffix: .html
    encoding: utf-8
  jackson:
    time-zone: GMT+8
    locale: zh_CN
    date-format: yyyy-MM-dd HH:mm:ss
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    #初始化表结构
    jdbc:
      initialize-schema: always
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: webiste.lhc.heron.model
  mail:
    host: smtp.qq.com
    username: 22222@qq.com
    password: inhlmdfqmlqfbfaf
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    webiste:
      lhc:
        heron: debug
mybatis:
  base-packages: webiste.lhc.heron.model
  mapper-locations: classpath:mapper/*.xml

minio:
  url: https://oss.222222.com/
  accessKey: 111
  secretKey: 1111

gaode:
  appkey: 1111111
  ipInfo:
    url: https://restapi.amap.com/v3/ip
  weather:
    url: https://restapi.amap.com/v3/weather/weatherInfo
